apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-metadata
spec:
  params:
    - name: snapshot
      description: 'The JSON string representing the snapshot of the application under test.'
      type: string
  steps:
    - name: echo
      image: alpine
      env:
        - name: SNAPSHOT
          value: $(params.snapshot)
      script: |
        #!/bin/sh
        echo "${SNAPSHOT}" 
